import SimpleITK as sitk
import numpy as np

# 이미지 크기 설정
size = (64, 64, 64)

# numpy array로 이미지 생성
image = np.zeros(size, dtype=np.uint8)

# 도형 생성
for z in range(20, 44):
    for y in range(20, 44):
        for x in range(20, 44):
            if (x-32)**2 + (y-32)**2 + (z-32)**2 <= 100:
                image[z,y,x] = (x+y+z)%8

# SimpleITK 이미지로 변환
sitk_image = sitk.GetImageFromArray(image)

# SimpleITK 이미지의 spacing 설정
sitk_image.SetSpacing((1.0, 1.0, 1.0))

# SimpleITK 이미지의 direction 설정
direction = np.identity(3, dtype=np.float64)
sitk_image.SetDirection(direction.flatten())

# metadata 설정
sitk_image.SetMetaData("Segment0_Color", "1 0.196078 0.196078")
sitk_image.SetMetaData("Segment0_ColorAutoGenerated", "1")
# sitk_image.SetMetaData("Segment0_Extent", "20 43 20 43 20 43")
sitk_image.SetMetaData("Segment0_ID", "Segment_1")
sitk_image.SetMetaData("Segment0_LabelValue", "1")
sitk_image.SetMetaData("Segment0_Layer", "0")
sitk_image.SetMetaData("Segment0_Name", "EDH")
sitk_image.SetMetaData("Segment0_NameAutoGenerated", "0")
sitk_image.SetMetaData("Segment0_Tags", "TerminologyEntry:Segmentation category and type - Heuron_cHS~SCT^85756007^Tissue~^^~^^~~^^~^^|")

sitk_image.SetMetaData("Segment1_Color", "0.101961 1 0")
sitk_image.SetMetaData("Segment1_ColorAutoGenerated", "0")
# sitk_image.SetMetaData("Segment1_Extent", "177 441 86 393 6 22")
sitk_image.SetMetaData("Segment1_ID", "Segment_2")
sitk_image.SetMetaData("Segment1_LabelValue", "2")
sitk_image.SetMetaData("Segment1_Layer", "0")
sitk_image.SetMetaData("Segment1_Name", "ICH")
sitk_image.SetMetaData("Segment1_NameAutoGenerated", "0")
sitk_image.SetMetaData("Segment1_Tags", "Segmentation.Status:inprogress|TerminologyEntry:Segmentation category and type - Heuron_cHS~SCT^85756007^Tissue~^^~^^~~^^~^^|")

sitk_image.SetMetaData("Segment2_Color", "1 0.972549 0.219608")
sitk_image.SetMetaData("Segment2_ColorAutoGenerated", "0")
# sitk_image.SetMetaData("Segment2_Extent", "177 441 86 393 6 22")
sitk_image.SetMetaData("Segment2_ID", "Segment_3")
sitk_image.SetMetaData("Segment2_LabelValue", "3")
sitk_image.SetMetaData("Segment2_Layer", "0")
sitk_image.SetMetaData("Segment2_Name", "IVH")
sitk_image.SetMetaData("Segment2_NameAutoGenerated", "0")
sitk_image.SetMetaData("Segment2_Tags", "Segmentation.Status:inprogress|TerminologyEntry:Segmentation category and type - Heuron_cHSSCT^85756007^Tissue^^^^~~^^^^|")

sitk_image.SetMetaData("Segment3_Color", "0.529412 0.882353 1")
sitk_image.SetMetaData("Segment3_ColorAutoGenerated", "0")
# sitk_image.SetMetaData("Segment3_Extent", "177 441 86 393 6 22")
sitk_image.SetMetaData("Segment3_ID", "Segment_4")
sitk_image.SetMetaData("Segment3_LabelValue", "4")
sitk_image.SetMetaData("Segment3_Layer", "0")
sitk_image.SetMetaData("Segment3_Name", "SAH")
sitk_image.SetMetaData("Segment3_NameAutoGenerated", "0")
sitk_image.SetMetaData("Segment3_Tags", "Segmentation.Status:inprogress|TerminologyEntry:Segmentation category and type - Heuron_cHSSCT^85756007^Tissue^^^^~~^^^^|")

sitk_image.SetMetaData("Segment4_Color", "1 0.396078 0.678431")
sitk_image.SetMetaData("Segment4_ColorAutoGenerated", "0")
# sitk_image.SetMetaData("Segment4_Extent", "177 441 86 393 6 22")
sitk_image.SetMetaData("Segment4_ID", "Segment_5")
sitk_image.SetMetaData("Segment4_LabelValue", "5")
sitk_image.SetMetaData("Segment4_Layer", "0")
sitk_image.SetMetaData("Segment4_Name", "SDH")
sitk_image.SetMetaData("Segment4_NameAutoGenerated", "0")
sitk_image.SetMetaData("Segment4_Tags", "TerminologyEntry:Segmentation category and type - Heuron_cHS~^^^^^^~~^^~^^|")

sitk_image.SetMetaData("Segment5_Color", "0.960784 0.180392 1")
sitk_image.SetMetaData("Segment5_ColorAutoGenerated", "0")
# sitk_image.SetMetaData("Segment5_Extent", "177 441 86 393 6 22")
sitk_image.SetMetaData("Segment5_ID", "Segment_6")
sitk_image.SetMetaData("Segment5_LabelValue", "6")
sitk_image.SetMetaData("Segment5_Layer", "0")
sitk_image.SetMetaData("Segment5_Name", "SDH(Chronic)")
sitk_image.SetMetaData("Segment5_NameAutoGenerated", "0")
sitk_image.SetMetaData("Segment5_Tags", "TerminologyEntry:Segmentation category and type - Heuron_cHSSCT^85756007^Tissue^^^^~~^^^^|")

sitk_image.SetMetaData("Segment6_Color", "0 0.34902 1")
sitk_image.SetMetaData("Segment6_ColorAutoGenerated", "0")
# sitk_image.SetMetaData("Segment6_Extent", "177 441 86 393 6 22")
sitk_image.SetMetaData("Segment6_ID", "Segment_7")
sitk_image.SetMetaData("Segment6_LabelValue", "7")
sitk_image.SetMetaData("Segment6_Layer", "0")
sitk_image.SetMetaData("Segment6_Name", "HemorrhagicContusion")
sitk_image.SetMetaData("Segment6_NameAutoGenerated", "0")
sitk_image.SetMetaData("Segment6_Tags", "Segmentation.Status:inprogress|TerminologyEntry:Segmentation category and type - Heuron_cHSSCT^85756007^Tissue^^^^~~^^^^|")

# nrrd 파일로 저장
sitk.WriteImage(sitk_image, 'output.nrrd', useCompression=False)
